### ISSUE TITLE
Battery levels

### ISSUE THREAD

**Issue by readeral** [nathankunicki/nuimojs#25]
Hi Nathan, thanks for this library, it's excellent and I'm hoping to complete a node-red package in the next few days that uses it as a dependency, rather than previous attempts that went the 'roll-your-own' route and fizzled out...

I do wonder though about the Nuimo battery level. At the moment when getting device.batteryLevel for my Nuimo, it's returning 100, despite the fact I've had it off charge for 4-5 days and at least 48 hours of that time has been connected (admittedly via BLE but...) to a RPi3, and I've been clicking and interacting with it a fair bit.

That seems odd to me. Is it possible that there's been a firmware change since this library coded the battery level that means it's giving an inaccurate value?

**Comment by readeral** [comment]
Hmm I shouldn't have been so quick to open an issue!!

Now it's reporting 97%, so I guess it's just super efficient! - or the device isn't great at reporting it's own battery, given it went from 100 to 97.

What has your experience been of the battery reporting?

**Comment by nathankellenicki** [comment]
Thanks! Glad you find the library useful.

Admittedly I haven't tried looking at the battery status for a while (when mine just stops working, I just charge it overnight), but last time I looked it was working fine. Has yours gone down any further?

I think the library might report 100 for a while until the first battery report comes in from the device, which might take a while as I think it only sends reports when the battery level changes. This is a good point - I might change it so that it does a "read" on first connect instead of waiting for "notifies".

Unfortunately my Nuimo's are in a container by sea at the moment as I'm moving country! So it may be a couple of months until I'm able to look at this.

**Comment by readeral** [comment]
So having spent a few more days with it, I'm seeing far more normal battery behaviour, except for that initial report of 100 as you mention. All is well :) Just seems the Nuimo does the classic battery thing of reporting discharge less than linearly.

Thanks for responding! I'll close this issue.
